### ISSUE TITLE
`no-renaming-operator` rule

### ISSUE THREAD

**Issue by shumbo** [shumbo/choreography-ts#19]
Choreography.ts expects developers to use the [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) syntax to receive operators. I believe this is a reasonable assumption and makes it easy to write other rules.

### ✅

```tsx
const test: Choreography<Locations> = async ({
  locally,
}) => {
  await locally("alice", () => {
    console.log("Hi from Alice");
  });
  return [];
};
```

### ❌

```tsx
const test: Choreography<Locations> = async (operators) => {
  await operators.locally("alice", () => {
    console.log("Hi from Alice");
  });
  return [];
};
```

```tsx
const test: Choreography<Locations> = async ({locally: l}) => {
  await l("alice", () => {
  	console.log("Hi from Alice");
  });
  return [];
};
```

**Comment by ImpregnableProgrammer** [comment]
This is being worked on with pull request #24

**Comment by ImpregnableProgrammer** [comment]
This is now completed and can be closed.
