### ISSUE TITLE
Example: `diffiehellman`

### ISSUE THREAD

**Issue by shumbo** [shumbo/choreography-ts#20]
Port the Diffie-Hellman example from HasChor (and Choral).

- [HasChor implementation](https://github.com/gshen42/HasChor/blob/42ae1ef9a500dadd82f0cfe5dee3c2aa631d8f4d/examples/diffiehellman/Main.hs)
- [Choral Implementation](https://github.com/choral-lang/examples/blob/8767c022272d1757de356cabaf6cbeb8bcfc556d/choral/diffie-hellman/DiffieHellman.ch)

**Comment by ImpregnableProgrammer** [comment]
#21 This should be done now along with the testing for it
